config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'hide_journal/:journal_id', to: 'journals#hide_journal', as: 'hide_journal'

app/views/issues/_action_menu.html.erb
<div class="contextual">
  <% if User.current.admin? %>
    <%= link_to issue_path(@issue, show_hidden_journals: true), title: 'Show hidden journals' do %>
      <%= image_tag 'opera-glasses.png', plugin: 'redmine_hide_journal' %>
    <% end %>
  <% end %>
  <%= link_to l(:button_edit), edit_issue_path(@issue), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @issue.editable? %>
  <%= link_to l(:button_log_time), new_issue_time_entry_path(@issue), :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project) %>
  <%= watcher_link(@issue, User.current) %>
  <%= link_to l(:button_copy), project_copy_issue_path(@project, @issue), :class => 'icon icon-copy' if User.current.allowed_to?(:copy_issues, @project) && Issue.allowed_target_projects.any? %>
  <%= link_to l(:button_delete), issue_path(@issue), :data => {:confirm => issues_destroy_confirmation_message(@issue)}, :method => :delete, :class => 'icon icon-del' if @issue.deletable? %>
</div>

app/views/issues/_history.html.erb
<% reply_links = issue.notes_addable? -%>
<% for journal in journals %>
  <div id="change-<%= journal.id %>" class="<%= journal.css_classes %>">
    <div id="note-<%= journal.indice %>">
      <h4><a href="#note-<%= journal.indice %>" class="journal-link">#<%= journal.indice %></a>
        <% if User.current.admin? %>
          <% if journal.is_hidden == false %>
            <%= link_to hide_journal_path(journal_id: journal.id, show: false), class: 'journal-link', style: 'margin-right: 10px;', title: 'hide' do %>
              <%= image_tag 'delete.png' %>
            <% end %>
          <% else %>
            <%= link_to hide_journal_path(journal_id: journal.id, show: true), class: 'journal-link', style: 'margin-right: 10px;', title: 'show' do %>
              <%= image_tag 'opera-glasses.png', plugin: 'redmine_hide_journal' %>
            <% end %>
          <% end %>
        <% end %>
        <%= avatar(journal.user, :size => "24") %>
        <%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %>
        <%= render_private_notes_indicator(journal) %>
      </h4>

      <% if journal.details.any? %>
        <ul class="details">
          <% details_to_strings(journal.visible_details).each do |string| %>
            <li><%= string %></li>
          <% end %>
        </ul>
        <% if Setting.thumbnails_enabled? && (thumbnail_attachments = journal_thumbnail_attachments(journal)).any? %>
          <div class="thumbnails">
            <% thumbnail_attachments.each do |attachment| %>
              <div><%= thumbnail_tag(attachment) %></div>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <%= render_notes(issue, journal, :reply_links => reply_links) unless journal.notes.blank? %>
    </div>
  </div>
  <%= call_hook(:view_issues_history_journal_bottom, { :journal => journal }) %>
<% end %>

<% heads_for_wiki_formatter if User.current.allowed_to?(:edit_issue_notes, issue.project) || User.current.allowed_to?(:edit_own_issue_notes, issue.project) %>